# App package for semantic support bot

from app.exceptions import (
    BotError,
    ModelLoadError,
    CacheError,
    CacheCorruptionError,
    IndexBuildError,
    InferenceError,
    InferenceTimeoutError,
    BatcherError,
    BatcherNotRunningError,
    KnowledgeBaseError,
    KnowledgeBaseEmptyError,
    QAFileError,
    QAFileParseError,
    SearchError,
    FaissIndexError,
    ValidationError,
    EmptyInputError,
    InputTooLongError,
    ContentModerationError,
)

__all__ = [
    "BotError",
    "ModelLoadError",
    "CacheError",
    "CacheCorruptionError",
    "IndexBuildError",
    "InferenceError",
    "InferenceTimeoutError",
    "BatcherError",
    "BatcherNotRunningError",
    "KnowledgeBaseError",
    "KnowledgeBaseEmptyError",
    "QAFileError",
    "QAFileParseError",
    "SearchError",
    "FaissIndexError",
    "ValidationError",
    "EmptyInputError",
    "InputTooLongError",
    "ContentModerationError",
]
